[enb]
enb_id = 0x19C
mcc = 901
mnc = 70
mme_addr = 127.0.0.1
gtp_bind_addr = 127.0.0.1
s1c_bind_addr = 127.0.0.1
n_prb = 50

[enb_files]
sib_config = sib2.conf
rr_config = rr2.conf
drb_config = drb.conf

[rf]
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://*:2100,rx_port=tcp://localhost:2101,id=enb2,base_srate=23.04e6

[expert]
a3_offset = 3
a3_hysteresis = 1
time_to_trigger = 320
